services:
  cuboid:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cuboid
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --origincert /etc/cloudflared/cert.pem --config /tunnel/config.yml run cuboid
    volumes:
      - ./cloudflared.yml:/tunnel/config.yml:ro
      - ${HOME}/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - cuboid
