services:
  cuboid:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cuboid
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --origincert /etc/cloudflared/cert.pem --config /tunnel/config.yml run cuboid
    volumes:
      - ./cloudflared.yml:/tunnel/config.yml:ro
      - /home/siphyshu/.cloudflared/cert.pem:/etc/cloudflared/cert.pem:ro
      - /usr/local/etc/cloudflared/634ae960-68b8-4e84-a7a0-5881a665c3fa.json:/etc/cloudflared/634ae960-68b8-4e84-a7a0-5881a665c3fa.json:ro
    depends_on:
      - cuboid
